CREATE TABLE CARS(UID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
				 REG_SYBMOL VARCHAR(15) NULL,
				 VIN VARCHAR(20) NULL,
				 MODEL VARCHAR(50) NULL,
				 TYPE_TC VARCHAR(30) NULL,
				 CATEGORY VARCHAR(5) NULL,
				 MADEYEAR INT DEFAULT 0 NULL,
				 CARCASS VARCHAR(40) NULL,
				 COLOR VARCHAR(40) NULL,
				 MOTOR_POWER FLOAT DEFAULT 0,
				 ECOLOGY VARCHAR(30) NULL,
				 RESERVE BIT NULL,
				 DOC_NUM INT NOT NULL,
				 DOC_SERIAL INT NOT NULL
				 
				 
				 
) 

CREATE TABLE CARS_DETAIL(ROWID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
						 UID_CARS INT NOT NULL,
						 PASSPORT_NUM INT NULL,
						 PASSPORT_SERIAL INT NULL,
						 MASS_MAX FLOAT NULL,
						 MASS_LOADOUT FLOAT NULL,
				 
				 
						 INS_NUM INT NULL,
						 INS_SERIAL INT NULL,
						 BEG_DATE SMALLDATETIME NULL,
						 END_DATE SMALLDATETIME NULL, 
						 
						 
						 CHASSIS VARCHAR(15) NULL,
						 WORKSTATE VARCHAR(30) NULL,
						 PRIMECH VARCHAR(200) NULL



)